/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    This script analyzes the magnitude of key business metrics across
    different dimensions .

SQL Functions Used:
    - SUM()      : Calculates totals.
    - COUNT()    : Counts records within each group.
    - AVG()      : Calculates average values.
    - GROUP BY   : Aggregates data by dimension.
    - ORDER BY   : Sorts aggregated results.
===============================================================================
*/


-- ============================================================================
-- Customer Distribution by Country
-- ============================================================================
-- Counts the number of customers in each country.

SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- ============================================================================
-- Customer Distribution by Gender
-- ============================================================================
-- Counts the number of customers by gender.

SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- ============================================================================
-- Product Distribution by Category
-- ============================================================================
-- Counts the number of products available in each category.

SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- ============================================================================
-- Average Product Cost by Category
-- ============================================================================
-- Calculates the average product cost within each product category.

SELECT
    category,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- ============================================================================
-- Revenue by Product Category
-- ============================================================================
-- Calculates the total sales revenue generated by each product category.

SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- ============================================================================
-- Revenue by Customer
-- ============================================================================
-- Calculates the lifetime revenue generated by each customer.

SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- ============================================================================
-- Sales Volume by Country
-- ============================================================================
-- Calculates the total quantity of products sold in each country.

SELECT
    c.country,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity_sold DESC;
